[package]
name = "ssc"
version = "0.0.0"
authors = ["KNP Labs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
