version: 2

reference:
  vm_machine: &vm_machine
    working_directory: ~/should-skip-ci
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true

  checkout_step: &checkout_step
    checkout:
      path: ~/should-skip-ci

  restore_cache_step: &restore_cache_step
    restore_cache:
      keys:
        - cargo-v3-{{ checksum "Cargo.lock" }}
        - cargo-v3-

  enlight_cache_step: &enlight_cache_step
    run:
      name: Enlight cache
      # @see https://docs.travis-ci.com/user/languages/rust/#dependency-management
      # Use sudo due to the different uid between circleci user and docker user
      command: sudo rm -rf .cargo/registry/src

  save_cache_step: &save_cache_step
    save_cache:
      key: cargo-v3-{{ checksum "Cargo.lock" }}
      paths:
        - .cargo/
        - target/

  build_docker_image_step: &build_docker_image_step
    run:
      name: Build docker image
      command: make build

  chown_working_directory_step: &chown_working_directory_step
    run:
      name: Chown working directory
      command: |
        # Change the owner of the whole project as CircleCI run with
        # uid 1001 but uid 1000 is used in the containers.
        sudo chown -R 1000 .

  run_unit_tests_step: &run_unit_tests_step
    run:
      name: Run unit tests
      command: make test-unit

  run_functional_tests_step: &run_functional_tests_step
    run:
      name: Run functional tests
      command: make test-functional

  build_release_step: &build_release_step
    run:
      name: Build release
      command: make build-release

  upload_release_asset_step: &upload_release_asset_step
    run:
      name: Upload release asset
      command: GIT_TAG=${CIRCLE_TAG} SSC_BIN=target/release/ssc .circleci/upload_release_asset.sh

jobs:
  test_job:
    <<: *vm_machine
    steps:
      - <<: *checkout_step
      - <<: *build_docker_image_step
      - <<: *restore_cache_step
      - <<: *chown_working_directory_step
      - <<: *run_unit_tests_step
      - <<: *run_functional_tests_step
      - <<: *enlight_cache_step
      - <<: *save_cache_step

  release_job:
    <<: *vm_machine
    steps:
      - <<: *checkout_step
      - <<: *build_docker_image_step
      - <<: *restore_cache_step
      - <<: *chown_working_directory_step
      - <<: *build_release_step
      - <<: *upload_release_asset_step

workflows:
  version: 2

  test:
    jobs:
      - test_job

  release:
    jobs:
      - release_job:
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /v.*/ }
