name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: make build
      - name: Run tests
        run: make tests
    runs-on: ["self-hosted", "2GB"]
